### ISSUE TITLE
No way to listen for changes to `this.element`

### ISSUE THREAD

**Issue by emattias** [ember-modifier/ember-modifier#174]
I built [a modifier](https://gist.github.com/emattias/5cf683aa329d42104fdab490102b035f#file-modifiers-custom-modifier-js) heavily based on @miguelcobain:s [css-transitions modifier](https://github.com/peec/ember-css-transitions/blob/master/addon/modifiers/css-transition.js).

It lets you animate an element out by cloning it and keeping track of an elements `nextElementSibling` and insert the clone before it.

In this example I have an `ember-dragula` list implemented and every item in the list uses my [custom-modifier](https://ember-twiddle.com/5cf683aa329d42104fdab490102b035f?openFiles=modifiers.custom-modifier%5C.js%2C).

I was able to work around it by adding a [MutationObserver](https://gist.github.com/emattias/5cf683aa329d42104fdab490102b035f#file-controllers-application-js-L37-L41) tracking removed nodes in the list and sending that array of removed nodes as an argument which triggers `didUpdateArguments` and in that [I update nextElementSiblings](https://gist.github.com/emattias/5cf683aa329d42104fdab490102b035f#file-modifiers-custom-modifier-js-L29-L36). This fixes this problem, see video, showing the bug. 

In the [twiddle](https://ember-twiddle.com/5cf683aa329d42104fdab490102b035f) I add a green outline for 3 seconds when an element is removed. Notice how when the mutation observer the outline is on the wrong element for the second deleted item:

### MutationObserver off
https://user-images.githubusercontent.com/351537/153926785-5bf00247-e7c4-482b-b637-0c0e2674324b.mp4

### MutationObserver on
https://user-images.githubusercontent.com/351537/153926806-aa6c656c-3ad2-4c13-80f7-874718c2be98.mp4

Maybe we could add something like a `didUpdateElement` event or have `this.element` changes trigger `didUpdateArguments`?

**Comment by emattias** [comment]
A better solution might be if we could hook in right before `this.element` is removed from the dom.  That way we would not need to [save the nextElementSibling](https://gist.github.com/emattias/5cf683aa329d42104fdab490102b035f#file-modifiers-custom-modifier-js-L23) on `didInstall`.

But if we can't add a hook to right before the element is removed the from the dom I guess hooking in everytime this.element is changed would also work.

**Comment by chriskrycho** [comment]
Interesting use case! I'm actually moving this over to the Ember.js RFCs repo for discussion there, because it's a limitation of the underlying infrastructure, *not* of this addon. The framework doesn't actually call a modifier manager when the element changes—instead, as your implementation (and the one in CSS Transitions it is based on) uses, it actually *tears down* the modifier when the element is going to be removed.

---

As a general recommendation for this kind of thing, I would probably reach for a shared state bucket (whether via a service or otherwise) which can actually handle the mechanics of DOM cloning and cleanup, where the modifier itself basically registers the elements on `didInstall` and indicates that it should schedule the clone-and-removal via `willDestroy`. In other words, more or less the way you're using a `MutationObserver` here! And given that you can do exactly that, I don't *think* we would want to change the semantics here, but I will leave it open for discussion and input from others.

**Comment by chriskrycho** [comment]
Update: I cannot transfer it because I don’t *own* the Ember RFCs repo :joy: so I'm going to close it here and you should feel free to copy and open it there.
