### ISSUE TITLE
Ember modifier broke in each loop

### ISSUE THREAD

**Issue by amk221** [ember-modifier/ember-modifier#505]
This is one of those issues I'm not sure is really anything to do with ember-modifier, and more suited for discord. But I've exhausted that avenue. So appologies if this is the wrong place.

Consider this modifier:

```javascript
item = modifier(
  (element) => {
    const handler = () => console.log('clicked');

    element.addEventListener('click', handler);

    return () => {
      element.removeEventListener('click', handler);
    };
  },
  { eager: false }
);
```

And it's rendered in an each loop

```handlebars
<ul>
  {{#each this.filteredGroups as |group|}}
    <li>
      {{group.title}}

      <ul>
        {{#each group.items as |item|}}
          <li {{this.item}}>
            {{item.name}}
          </li>
        {{/each}}
      </ul>
    </li>
  {{/each}}
</ul>
```

The modifier works fine initially, but when filtering the list, the modifier doesn't get re-set up as the each loop changes.

Here is a [video](https://share.getcloudapp.com/9ZugJvKe) showing the click handler not running.
Here is a [demo app](https://github.com/amk221/-ember-modifier-each-example/blob/main/app/controllers/application.js#L30-L41)

This can be 'fixed' by setting a `key=` on the each loop.

But is that the right thing to do? I feel like it should 'just work' without having to do that.

**Comment by NullVoxPopuli** [comment]
cross-linking here: https://github.com/emberjs/ember.js/issues/20255

**Comment by chriskrycho** [comment]
This is expected behavior: Ember uses (and in fact explicitly says in the docs for `each` that it uses!) object identity by default for deciding whether an item in a loop has changed and needs to be rerendered. The filtering does not change the identity of the items here, it only shows which ones are present. If we didn’t do this, we would have to always require a key to keep from defending needlessly: compare how React does exactly that. Net, we can avoid a looooot of needless rerenders, and the default case does “what it should” as a result; while you have the ability to opt into a different behavior with `key`.

**Comment by amk221** [comment]
Thank you

**Comment by amk221** [comment]
Just as a note... if you write a test to do the same thing that happens in the video (filter, then click)
The modifier is reapplied without the need for `@index`

That's confusing?

**Comment by NullVoxPopuli** [comment]
How do you mean? Can you add code to this thread?

**Comment by amk221** [comment]
Sure,

I have added a test here: https://github.com/amk221/-ember-modifier-each-example/blob/166373396b5537c371335abe7c9eefe55d4980ab/tests/acceptance/application-test.js#L26-L42
